#!/usr/bin/env bash
# Install the clone-contracts skill globally so it works from any directory.
#
# What this does:
#   1. Creates ~/.claude/skills/clone-contracts/ as the install directory.
#   2. Symlinks SKILL.md and clone_external.py from this repo into the install
#      directory so `git pull` updates propagate automatically.
#   3. Creates a Python venv at ~/.claude/skills/clone-contracts/.venv with
#      requests + python-dotenv installed.
#   4. Drops a `clone-external` wrapper into ~/.local/bin/ that invokes the
#      venv python + clone_external.py.
#   5. Prompts for ETHERSCAN_API_KEY if one isn't already configured.
#
# Re-running is safe; all steps are idempotent.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DEST="${HOME}/.claude/skills/clone-contracts"
BIN_DIR="${HOME}/.local/bin"
WRAPPER="${BIN_DIR}/clone-external"
VENV_DIR="${SKILL_DEST}/.venv"
ENV_FILE="${SKILL_DEST}/.env"

log()  { printf '  %s\n' "$*"; }
step() { printf '\n▸ %s\n' "$*"; }

# --- sanity checks --------------------------------------------------------
[[ -f "${REPO_ROOT}/SKILL.md" ]]          || { echo "ERROR: ${REPO_ROOT}/SKILL.md not found"; exit 1; }
[[ -f "${REPO_ROOT}/clone_external.py" ]] || { echo "ERROR: ${REPO_ROOT}/clone_external.py not found"; exit 1; }
command -v python3 >/dev/null             || { echo "ERROR: python3 not on PATH"; exit 1; }

# --- 1. install directory -------------------------------------------------
step "Preparing install directory ${SKILL_DEST}"
mkdir -p "${SKILL_DEST}"
log "install dir ready"

# --- 2. symlink SKILL.md and clone_external.py ---------------------------
step "Linking skill files from ${REPO_ROOT}"
for name in SKILL.md clone_external.py; do
    link="${SKILL_DEST}/${name}"
    target="${REPO_ROOT}/${name}"
    ln -sfn "${target}" "${link}"
    log "${link} → ${target}"
done

# --- 3. venv + deps -------------------------------------------------------
step "Setting up Python venv at ${VENV_DIR}"
if [[ ! -x "${VENV_DIR}/bin/python" ]]; then
    python3 -m venv "${VENV_DIR}"
    log "created venv"
else
    log "venv already exists"
fi

"${VENV_DIR}/bin/pip" install --quiet --upgrade pip
"${VENV_DIR}/bin/pip" install --quiet requests python-dotenv
log "installed requests + python-dotenv"

# --- 4. wrapper command ---------------------------------------------------
step "Installing wrapper at ${WRAPPER}"
mkdir -p "${BIN_DIR}"
cat > "${WRAPPER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by clone-contracts-skill/setup.sh. Do not edit.
exec "${VENV_DIR}/bin/python" "${SKILL_DEST}/clone_external.py" "\$@"
EOF
chmod +x "${WRAPPER}"
log "wrote ${WRAPPER}"

case ":${PATH}:" in
    *":${BIN_DIR}:"*) ;;
    *) log "WARNING: ${BIN_DIR} is not on PATH — add it to your shell rc to use 'clone-external'." ;;
esac

# --- 5. ETHERSCAN_API_KEY -------------------------------------------------
step "Configuring ETHERSCAN_API_KEY"
if [[ -f "${ENV_FILE}" ]] && grep -q '^ETHERSCAN_API_KEY=' "${ENV_FILE}"; then
    log "${ENV_FILE} already has ETHERSCAN_API_KEY"
elif [[ -n "${ETHERSCAN_API_KEY:-}" ]]; then
    printf 'ETHERSCAN_API_KEY=%s\n' "${ETHERSCAN_API_KEY}" > "${ENV_FILE}"
    chmod 600 "${ENV_FILE}"
    log "seeded from \$ETHERSCAN_API_KEY env var"
elif [[ -t 0 ]]; then
    # Interactive terminal: prompt for the key.
    log "Get a free Etherscan API key at https://etherscan.io/apis"
    read -rsp "  Paste ETHERSCAN_API_KEY (or press Enter to skip): " key
    echo
    if [[ -n "${key}" ]]; then
        printf 'ETHERSCAN_API_KEY=%s\n' "${key}" > "${ENV_FILE}"
        chmod 600 "${ENV_FILE}"
        log "saved to ${ENV_FILE}"
    else
        log "skipped; set one later with:"
        log "  echo 'ETHERSCAN_API_KEY=<your-key>' > ${ENV_FILE}"
    fi
else
    log "no key found and stdin is not a TTY; set one with:"
    log "  echo 'ETHERSCAN_API_KEY=<your-key>' > ${ENV_FILE}"
fi

step "Done."
echo "  Try it:  clone-external --chain ethereum uniswap:0x1F98431c8aD98523631AE4a59f267346ea31F984"
