#!/usr/bin/env python3
"""
SolidityGuard Report Generator

Generates professional security audit reports from scan results.
Supports Markdown and PDF output in OpenZeppelin/Trail of Bits style.

Usage:
    python3 report_generator.py results.json --output report.md
    python3 report_generator.py results.json --output report.md --pdf
    python3 report_generator.py results.json --output report.md --project "DeFi Protocol" --client "Acme Corp"
"""

import argparse
import html
import json
import os
import subprocess
import sys
from datetime import datetime


SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"]
SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🔵",
    "INFORMATIONAL": "⚪",
}
SEVERITY_COLORS = {
    "CRITICAL": "#ef4444",
    "HIGH": "#f97316",
    "MEDIUM": "#eab308",
    "LOW": "#3b82f6",
    "INFORMATIONAL": "#6b7280",
}

PDF_CSS = """
@page {
    size: A4;
    margin: 2cm 2.5cm 2.5cm 2.5cm;
    @bottom-center {
        content: "Generated by SolidityGuard -- Solidity Security Audit Tool";
        font-size: 8pt;
        color: #6b7280;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    }
    @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 8pt;
        color: #6b7280;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    }
}

@page :first {
    @bottom-center { content: none; }
    @bottom-right { content: none; }
}

* {
    box-sizing: border-box;
}

body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 10pt;
    line-height: 1.6;
    color: #1a1a2e;
    margin: 0;
    padding: 0;
}

/* Cover page */
.cover-page {
    page-break-after: always;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    min-height: 85vh;
    text-align: center;
}

.cover-logo {
    background: #0a0a0a;
    color: #ffffff;
    padding: 20px 50px;
    font-size: 28pt;
    font-weight: 700;
    letter-spacing: 2px;
    margin-bottom: 10px;
}

.cover-logo .accent {
    color: #3b82f6;
}

.cover-subtitle {
    font-size: 11pt;
    color: #6b7280;
    margin-bottom: 50px;
    letter-spacing: 1px;
}

.cover-title {
    font-size: 22pt;
    font-weight: 700;
    color: #0a0a0a;
    margin-bottom: 8px;
}

.cover-project {
    font-size: 16pt;
    color: #374151;
    margin-bottom: 50px;
}

.cover-meta {
    font-size: 10pt;
    color: #6b7280;
    line-height: 2;
}

.cover-meta strong {
    color: #374151;
}

/* Score badge on cover */
.score-badge {
    display: inline-block;
    padding: 12px 30px;
    border-radius: 8px;
    font-size: 18pt;
    font-weight: 700;
    color: #ffffff;
    margin: 30px 0;
}

.score-critical { background: #ef4444; }
.score-high { background: #f97316; }
.score-medium { background: #eab308; color: #1a1a2e; }
.score-low { background: #3b82f6; }
.score-minimal { background: #22c55e; }

/* Table of contents */
.toc {
    page-break-after: always;
}

.toc h2 {
    border-bottom: 2px solid #0a0a0a;
    padding-bottom: 8px;
}

.toc ol {
    list-style: none;
    padding: 0;
    counter-reset: toc-counter;
}

.toc ol li {
    counter-increment: toc-counter;
    padding: 8px 0;
    border-bottom: 1px solid #e5e7eb;
    font-size: 11pt;
}

.toc ol li::before {
    content: counter(toc-counter) ". ";
    font-weight: 700;
    color: #3b82f6;
}

/* Section headers */
h1 {
    font-size: 20pt;
    color: #0a0a0a;
    border-bottom: 3px solid #3b82f6;
    padding-bottom: 8px;
    margin-top: 30px;
}

h2 {
    font-size: 15pt;
    color: #0a0a0a;
    border-bottom: 1px solid #d1d5db;
    padding-bottom: 6px;
    margin-top: 24px;
}

h3 {
    font-size: 12pt;
    color: #1e3a5f;
    margin-top: 18px;
}

h4 {
    font-size: 11pt;
    color: #374151;
    margin-top: 14px;
}

/* Section breaks */
.section-break {
    page-break-before: always;
}

/* Tables */
table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 9pt;
}

th {
    background: #0a0a0a;
    color: #ffffff;
    padding: 8px 10px;
    text-align: left;
    font-weight: 600;
    font-size: 9pt;
}

td {
    padding: 6px 10px;
    border-bottom: 1px solid #e5e7eb;
}

tr:nth-child(even) td {
    background: #f9fafb;
}

/* Severity badges */
.severity-badge {
    display: inline-block;
    padding: 2px 10px;
    border-radius: 4px;
    font-size: 8pt;
    font-weight: 700;
    color: #ffffff;
    text-transform: uppercase;
}

.severity-CRITICAL { background: #ef4444; }
.severity-HIGH { background: #f97316; }
.severity-MEDIUM { background: #eab308; color: #1a1a2e; }
.severity-LOW { background: #3b82f6; }
.severity-INFORMATIONAL { background: #6b7280; }

/* Finding cards */
.finding-card {
    border: 1px solid #e5e7eb;
    border-radius: 6px;
    margin: 16px 0;
    page-break-inside: avoid;
    overflow: hidden;
}

.finding-header {
    padding: 10px 14px;
    color: #ffffff;
    font-weight: 700;
    font-size: 11pt;
}

.finding-header-CRITICAL { background: #ef4444; }
.finding-header-HIGH { background: #f97316; }
.finding-header-MEDIUM { background: #eab308; color: #1a1a2e; }
.finding-header-LOW { background: #3b82f6; }
.finding-header-INFORMATIONAL { background: #6b7280; }

.finding-body {
    padding: 14px;
}

.finding-meta {
    display: flex;
    gap: 20px;
    margin-bottom: 10px;
    font-size: 9pt;
    color: #6b7280;
}

.finding-meta strong {
    color: #374151;
}

/* Code blocks */
pre {
    background: #1e1e2e;
    color: #cdd6f4;
    padding: 12px 14px;
    border-radius: 4px;
    font-family: 'Courier New', Courier, monospace;
    font-size: 8.5pt;
    line-height: 1.5;
    overflow-x: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
}

code {
    font-family: 'Courier New', Courier, monospace;
    font-size: 9pt;
    background: #f1f5f9;
    padding: 1px 4px;
    border-radius: 3px;
    color: #be185d;
}

pre code {
    background: none;
    padding: 0;
    color: inherit;
}

/* Summary cards */
.summary-grid {
    display: flex;
    gap: 12px;
    margin: 16px 0;
    flex-wrap: wrap;
}

.summary-card {
    flex: 1;
    min-width: 100px;
    border: 1px solid #e5e7eb;
    border-radius: 6px;
    padding: 12px;
    text-align: center;
}

.summary-card .count {
    font-size: 22pt;
    font-weight: 700;
    display: block;
}

.summary-card .label {
    font-size: 8pt;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}

/* Confidence bar */
.confidence-bar-bg {
    width: 100px;
    height: 8px;
    background: #e5e7eb;
    border-radius: 4px;
    display: inline-block;
    vertical-align: middle;
}

.confidence-bar-fill {
    height: 100%;
    border-radius: 4px;
    background: #22c55e;
}

/* Recommendations */
.rec-list {
    list-style: none;
    padding: 0;
}

.rec-list li {
    padding: 6px 0 6px 20px;
    position: relative;
    border-bottom: 1px solid #f3f4f6;
}

.rec-list li::before {
    content: ">";
    position: absolute;
    left: 0;
    color: #3b82f6;
    font-weight: 700;
}

/* Horizontal rule */
hr {
    border: none;
    border-top: 1px solid #d1d5db;
    margin: 20px 0;
}

/* Footer text */
.footer-text {
    text-align: center;
    font-size: 8pt;
    color: #9ca3af;
    margin-top: 30px;
    font-style: italic;
}
"""


def generate_report(data: dict, project: str = "", client: str = "") -> str:
    """Generate a professional Markdown audit report."""
    findings = data.get("findings", [])
    summary = data.get("summary", {})
    score = data.get("security_score", 100)
    timestamp = data.get("timestamp", datetime.now().isoformat())

    project = project or data.get("project", "Unknown Project")
    date_str = datetime.fromisoformat(timestamp).strftime("%B %d, %Y")

    # Risk level
    if score >= 90:
        risk_level = "Minimal Risk"
        recommendation = "Ready for deployment with monitoring"
    elif score >= 70:
        risk_level = "Low Risk"
        recommendation = "Fix findings before mainnet deployment"
    elif score >= 50:
        risk_level = "Medium Risk"
        recommendation = "Major remediation required before deployment"
    elif score >= 25:
        risk_level = "High Risk"
        recommendation = "Critical remediation needed — do not deploy"
    else:
        risk_level = "Critical Risk"
        recommendation = "DO NOT DEPLOY — fundamental security issues"

    report = f"""# Security Audit Report
## {project}

---

**Prepared by**: SolidityGuard Security Audit Tool
**Client**: {client or "N/A"}
**Date**: {date_str}
**Version**: 1.0

---

## Table of Contents
1. Executive Summary
2. Scope & Methodology
3. Findings Overview
4. Detailed Findings
5. Recommendations
6. Appendix

---

## 1. Executive Summary

### Overview
This report presents the findings of an automated security audit of **{project}**.
The audit was conducted using a combination of static analysis (Slither, Aderyn),
symbolic execution (Mythril), and automated review covering 104 vulnerability
patterns mapped to the SWC Registry and OWASP Smart Contract Top 10.

### Assessment Summary

| Metric | Value |
|--------|-------|
| Security Score | **{score}/100** |
| Risk Level | **{risk_level}** |
| Total Findings | {summary.get("total", 0)} |
| Critical | {summary.get("critical", 0)} |
| High | {summary.get("high", 0)} |
| Medium | {summary.get("medium", 0)} |
| Low | {summary.get("low", 0)} |
| Informational | {summary.get("informational", 0)} |

### Recommendation
**{recommendation}**

---

## 2. Scope & Methodology

### Tools Used
{chr(10).join(f"- **{t}**" for t in data.get("tools_used", ["slither", "aderyn", "patterns"]))}
- Automated review (104 vulnerability patterns)

### Methodology
1. **Automated Static Analysis** — Slither (90+ detectors) and Aderyn (100+ detectors)
2. **Pattern Matching** — 104 vulnerability patterns (ETH-001 to ETH-104)
3. **Manual Code Review** — Line-by-line analysis of critical functions
4. **Evidence Collection** — All findings include exact file:line citations

### Severity Classification

| Severity | Description |
|----------|-------------|
| {SEVERITY_EMOJI["CRITICAL"]} Critical | Direct loss of funds, protocol takeover |
| {SEVERITY_EMOJI["HIGH"]} High | Significant fund loss under conditions |
| {SEVERITY_EMOJI["MEDIUM"]} Medium | Limited impact, specific conditions |
| {SEVERITY_EMOJI["LOW"]} Low | Minor issues, best practices |
| {SEVERITY_EMOJI["INFORMATIONAL"]} Info | Code quality suggestions |

---

## 3. Findings Overview

### By Severity

| Severity | Count |
|----------|-------|
| {SEVERITY_EMOJI["CRITICAL"]} Critical | {summary.get("critical", 0)} |
| {SEVERITY_EMOJI["HIGH"]} High | {summary.get("high", 0)} |
| {SEVERITY_EMOJI["MEDIUM"]} Medium | {summary.get("medium", 0)} |
| {SEVERITY_EMOJI["LOW"]} Low | {summary.get("low", 0)} |
| {SEVERITY_EMOJI["INFORMATIONAL"]} Info | {summary.get("informational", 0)} |

### All Findings

| # | ID | Title | Severity | Location | Tool |
|---|-----|-------|----------|----------|------|
"""

    for i, f in enumerate(sorted(findings, key=lambda x: SEVERITY_ORDER.index(x.get("severity", "INFORMATIONAL"))), 1):
        loc = f"{f.get('file', '')}:{f.get('line', '')}" if f.get('file') else "N/A"
        report += f"| {i} | {f.get('id', 'N/A')} | {f.get('title', 'N/A')} | {f.get('severity', 'N/A')} | `{loc}` | {f.get('tool', 'N/A')} |\n"

    report += """
---

## 4. Detailed Findings

"""

    for severity in SEVERITY_ORDER:
        sev_findings = [f for f in findings if f.get("severity") == severity]
        if not sev_findings:
            continue

        report += f"### {SEVERITY_EMOJI[severity]} {severity} Findings\n\n"

        for f in sev_findings:
            report += f"""#### {f.get("id", "N/A")}: {f.get("title", "N/A")}

**Location**: `{f.get("file", "N/A")}:{f.get("line", "N/A")}`
**Confidence**: {f.get("confidence", 0):.0%}
**Tool**: {f.get("tool", "N/A")}
{f"**SWC**: {f['swc']}" if f.get("swc") else ""}

**Description**:
{f.get("description", "N/A")}

"""
            if f.get("code_snippet"):
                report += f"""**Code**:
```solidity
{f.get("code_snippet", "")}
```

"""

            report += f"""**Recommendation**:
{f.get("recommendation", "N/A")}

---

"""

    report += f"""## 5. Recommendations

### Immediate Actions (Pre-Deployment)
{"- Fix all CRITICAL and HIGH findings before deployment" if summary.get("critical", 0) + summary.get("high", 0) > 0 else "- No critical actions required"}

### Short-term (Within 30 days)
- Address MEDIUM findings
- Add comprehensive test coverage
- Run invariant/fuzz tests

### Long-term (Ongoing)
- Integrate security scanning in CI/CD
- Regular security reviews for changes
- Consider formal verification for critical paths
- Establish bug bounty program

---

## 6. Appendix

### A. Security Score Calculation
```
Score = 100 - (Critical × 15) - (High × 8) - (Medium × 3) - (Low × 1)
Final Score: {score}/100
```

### B. Tool Versions
- Slither: Latest
- Aderyn: Latest
- SolidityGuard: v1.0.0

### C. References
- [SWC Registry](https://swcregistry.io/)
- [ConsenSys Best Practices](https://consensys.github.io/smart-contract-best-practices/)
- [OWASP Smart Contract Top 10](https://owasp.org/www-project-smart-contract-top-10/)

---

*Generated by SolidityGuard — Solidity Security Audit Tool*
"""

    return report


def _score_class(score: int) -> str:
    """Return CSS class name for the security score."""
    if score >= 90:
        return "score-minimal"
    elif score >= 70:
        return "score-low"
    elif score >= 50:
        return "score-medium"
    elif score >= 25:
        return "score-high"
    return "score-critical"


def _build_html(data: dict, project: str = "", client: str = "") -> str:
    """Build a styled HTML document from scan results for PDF conversion."""
    findings = data.get("findings", [])
    summary = data.get("summary", {})
    score = data.get("security_score", 100)
    timestamp = data.get("timestamp", datetime.now().isoformat())

    project = project or data.get("project", "Unknown Project")
    client = client or data.get("client", "N/A")
    date_str = datetime.fromisoformat(timestamp).strftime("%B %d, %Y")

    if score >= 90:
        risk_level = "Minimal Risk"
        recommendation = "Ready for deployment with monitoring"
    elif score >= 70:
        risk_level = "Low Risk"
        recommendation = "Fix findings before mainnet deployment"
    elif score >= 50:
        risk_level = "Medium Risk"
        recommendation = "Major remediation required before deployment"
    elif score >= 25:
        risk_level = "High Risk"
        recommendation = "Critical remediation needed"
    else:
        risk_level = "Critical Risk"
        recommendation = "DO NOT DEPLOY -- fundamental security issues"

    sorted_findings = sorted(
        findings,
        key=lambda x: SEVERITY_ORDER.index(x.get("severity", "INFORMATIONAL"))
    )

    # Cover page
    cover = f"""
    <div class="cover-page">
        <div class="cover-logo">Solidity<span class="accent">Guard</span></div>
        <div class="cover-subtitle">SMART CONTRACT SECURITY AUDIT</div>
        <div class="cover-title">Security Audit Report</div>
        <div class="cover-project">{html.escape(project)}</div>
        <div class="score-badge {_score_class(score)}">{score}/100 &mdash; {risk_level}</div>
        <div class="cover-meta">
            <strong>Client:</strong> {html.escape(client)}<br>
            <strong>Date:</strong> {date_str}<br>
            <strong>Version:</strong> 1.0<br>
            <strong>Findings:</strong> {summary.get("total", 0)}
            (Critical: {summary.get("critical", 0)},
             High: {summary.get("high", 0)},
             Medium: {summary.get("medium", 0)},
             Low: {summary.get("low", 0)})
        </div>
    </div>
    """

    # Table of contents
    toc = """
    <div class="toc">
        <h2>Table of Contents</h2>
        <ol>
            <li>Executive Summary</li>
            <li>Scope &amp; Methodology</li>
            <li>Findings Overview</li>
            <li>Detailed Findings</li>
            <li>Recommendations</li>
            <li>Appendix</li>
        </ol>
    </div>
    """

    # Section 1: Executive summary
    tools_list = "".join(
        f"<li><strong>{html.escape(t)}</strong></li>"
        for t in data.get("tools_used", ["slither", "aderyn", "patterns"])
    )

    section1 = f"""
    <div class="section-break">
        <h1>1. Executive Summary</h1>
        <h3>Overview</h3>
        <p>This report presents the findings of an automated security audit of
        <strong>{html.escape(project)}</strong>. The audit was conducted using
        static analysis (Slither, Aderyn), symbolic execution (Mythril), and
        automated review covering 104 vulnerability patterns mapped to
        the SWC Registry and OWASP Smart Contract Top 10 (2025).</p>

        <h3>Assessment Summary</h3>
        <div class="summary-grid">
            <div class="summary-card">
                <span class="count" style="color: {SEVERITY_COLORS['CRITICAL']}">{summary.get("critical", 0)}</span>
                <span class="label">Critical</span>
            </div>
            <div class="summary-card">
                <span class="count" style="color: {SEVERITY_COLORS['HIGH']}">{summary.get("high", 0)}</span>
                <span class="label">High</span>
            </div>
            <div class="summary-card">
                <span class="count" style="color: {SEVERITY_COLORS['MEDIUM']}">{summary.get("medium", 0)}</span>
                <span class="label">Medium</span>
            </div>
            <div class="summary-card">
                <span class="count" style="color: {SEVERITY_COLORS['LOW']}">{summary.get("low", 0)}</span>
                <span class="label">Low</span>
            </div>
            <div class="summary-card">
                <span class="count">{summary.get("total", 0)}</span>
                <span class="label">Total</span>
            </div>
        </div>

        <table>
            <tr><th>Metric</th><th>Value</th></tr>
            <tr><td>Security Score</td><td><strong>{score}/100</strong></td></tr>
            <tr><td>Risk Level</td><td><strong>{risk_level}</strong></td></tr>
            <tr><td>Recommendation</td><td>{recommendation}</td></tr>
        </table>
    </div>
    """

    # Section 2: Scope & Methodology
    section2 = f"""
    <div class="section-break">
        <h1>2. Scope &amp; Methodology</h1>
        <h3>Tools Used</h3>
        <ul>{tools_list}
            <li>Automated review (104 vulnerability patterns)</li>
        </ul>

        <h3>Methodology</h3>
        <ol>
            <li><strong>Automated Static Analysis</strong> &mdash; Slither (90+ detectors) and Aderyn (100+ detectors)</li>
            <li><strong>Pattern Matching</strong> &mdash; 104 vulnerability patterns (ETH-001 to ETH-104)</li>
            <li><strong>Manual Code Review</strong> &mdash; Line-by-line analysis of critical functions</li>
            <li><strong>Evidence Collection</strong> &mdash; All findings include exact file:line citations</li>
        </ol>

        <h3>Severity Classification</h3>
        <table>
            <tr><th>Severity</th><th>Description</th></tr>
            <tr><td><span class="severity-badge severity-CRITICAL">Critical</span></td>
                <td>Direct loss of funds, protocol takeover</td></tr>
            <tr><td><span class="severity-badge severity-HIGH">High</span></td>
                <td>Significant fund loss under conditions</td></tr>
            <tr><td><span class="severity-badge severity-MEDIUM">Medium</span></td>
                <td>Limited impact, specific conditions</td></tr>
            <tr><td><span class="severity-badge severity-LOW">Low</span></td>
                <td>Minor issues, best practices</td></tr>
            <tr><td><span class="severity-badge severity-INFORMATIONAL">Info</span></td>
                <td>Code quality suggestions</td></tr>
        </table>
    </div>
    """

    # Section 3: Findings overview
    findings_table_rows = ""
    for i, f in enumerate(sorted_findings, 1):
        sev = f.get("severity", "INFORMATIONAL")
        loc = f"{f.get('file', '')}:{f.get('line', '')}" if f.get("file") else "N/A"
        findings_table_rows += f"""
            <tr>
                <td>{i}</td>
                <td>{html.escape(str(f.get('id', 'N/A')))}</td>
                <td>{html.escape(str(f.get('title', 'N/A')))}</td>
                <td><span class="severity-badge severity-{sev}">{sev}</span></td>
                <td><code>{html.escape(loc)}</code></td>
                <td>{html.escape(str(f.get('tool', 'N/A')))}</td>
            </tr>
        """

    section3 = f"""
    <div class="section-break">
        <h1>3. Findings Overview</h1>
        <table>
            <tr><th>#</th><th>ID</th><th>Title</th><th>Severity</th><th>Location</th><th>Tool</th></tr>
            {findings_table_rows}
        </table>
    </div>
    """

    # Section 4: Detailed findings
    section4 = '<div class="section-break"><h1>4. Detailed Findings</h1>'

    for severity in SEVERITY_ORDER:
        sev_findings = [f for f in findings if f.get("severity") == severity]
        if not sev_findings:
            continue

        section4 += f'<h2><span class="severity-badge severity-{severity}">{severity}</span> Findings</h2>'

        for f in sev_findings:
            sev = f.get("severity", "INFORMATIONAL")
            fid = html.escape(str(f.get("id", "N/A")))
            ftitle = html.escape(str(f.get("title", "N/A")))
            floc = html.escape(f"{f.get('file', 'N/A')}:{f.get('line', 'N/A')}")
            conf = f.get("confidence", 0)
            conf_pct = int(conf * 100) if conf <= 1 else int(conf)
            ftool = html.escape(str(f.get("tool", "N/A")))
            fdesc = html.escape(str(f.get("description", "N/A")))
            frec = html.escape(str(f.get("recommendation", "N/A")))
            swc_html = f'<strong>SWC:</strong> {html.escape(str(f["swc"]))}<br>' if f.get("swc") else ""

            code_html = ""
            if f.get("code_snippet"):
                code_html = f'<h4>Vulnerable Code</h4><pre><code>{html.escape(f["code_snippet"])}</code></pre>'

            section4 += f"""
            <div class="finding-card">
                <div class="finding-header finding-header-{sev}">{fid}: {ftitle}</div>
                <div class="finding-body">
                    <div class="finding-meta">
                        <span><strong>Location:</strong> <code>{floc}</code></span>
                        <span><strong>Confidence:</strong> {conf_pct}%
                            <span class="confidence-bar-bg">
                                <span class="confidence-bar-fill" style="width:{conf_pct}%"></span>
                            </span>
                        </span>
                        <span><strong>Tool:</strong> {ftool}</span>
                    </div>
                    {swc_html}
                    <h4>Description</h4>
                    <p>{fdesc}</p>
                    {code_html}
                    <h4>Recommendation</h4>
                    <p>{frec}</p>
                </div>
            </div>
            """

    section4 += "</div>"

    # Section 5: Recommendations
    immediate = (
        "Fix all CRITICAL and HIGH findings before deployment"
        if summary.get("critical", 0) + summary.get("high", 0) > 0
        else "No critical actions required"
    )
    section5 = f"""
    <div class="section-break">
        <h1>5. Recommendations</h1>
        <h3>Immediate Actions (Pre-Deployment)</h3>
        <ul class="rec-list"><li>{immediate}</li></ul>

        <h3>Short-term (Within 30 days)</h3>
        <ul class="rec-list">
            <li>Address MEDIUM findings</li>
            <li>Add comprehensive test coverage</li>
            <li>Run invariant/fuzz tests</li>
        </ul>

        <h3>Long-term (Ongoing)</h3>
        <ul class="rec-list">
            <li>Integrate security scanning in CI/CD</li>
            <li>Regular security reviews for changes</li>
            <li>Consider formal verification for critical paths</li>
            <li>Establish bug bounty program</li>
        </ul>
    </div>
    """

    # Section 6: Appendix
    section6 = f"""
    <div class="section-break">
        <h1>6. Appendix</h1>
        <h3>A. Security Score Calculation</h3>
        <pre><code>Score = 100 - (Critical x 15) - (High x 8) - (Medium x 3) - (Low x 1)
Final Score: {score}/100</code></pre>

        <h3>B. Tool Versions</h3>
        <ul>
            <li>Slither: Latest</li>
            <li>Aderyn: Latest</li>
            <li>SolidityGuard: v1.0.0</li>
        </ul>

        <h3>C. References</h3>
        <ul>
            <li>SWC Registry (swcregistry.io)</li>
            <li>ConsenSys Best Practices (consensys.github.io/smart-contract-best-practices/)</li>
            <li>OWASP Smart Contract Top 10 (owasp.org/www-project-smart-contract-top-10/)</li>
        </ul>
    </div>

    <div class="footer-text">
        Generated by SolidityGuard &mdash; Solidity Security Audit Tool
    </div>
    """

    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Security Audit Report - {html.escape(project)}</title>
    <style>{PDF_CSS}</style>
</head>
<body>
    {cover}
    {toc}
    {section1}
    {section2}
    {section3}
    {section4}
    {section5}
    {section6}
</body>
</html>"""

    return full_html


def generate_pdf(data: dict, pdf_path: str, project: str = "", client: str = "") -> bool:
    """Generate a styled PDF report from scan results.

    Tries weasyprint first, falls back to pandoc, then returns False.

    Args:
        data: Scan results dict with findings, summary, security_score.
        pdf_path: Output PDF file path.
        project: Project name override.
        client: Client name override.

    Returns:
        True if PDF was generated successfully, False otherwise.
    """
    html_content = _build_html(data, project, client)

    # Try weasyprint first
    try:
        import weasyprint
        wp_html = weasyprint.HTML(string=html_content)
        wp_html.write_pdf(pdf_path)
        return True
    except ImportError:
        print("[INFO] weasyprint not available, trying pandoc fallback...")
    except Exception as e:
        print(f"[WARN] weasyprint failed: {e}, trying pandoc fallback...")

    # Pandoc fallback: write HTML to temp file, convert with pandoc
    try:
        html_tmp = pdf_path.replace(".pdf", ".tmp.html")
        with open(html_tmp, "w") as f:
            f.write(html_content)
        subprocess.run(
            ["pandoc", html_tmp, "-o", pdf_path, "--pdf-engine=wkhtmltopdf"],
            capture_output=True, check=True
        )
        os.remove(html_tmp)
        return True
    except FileNotFoundError:
        print("[WARN] pandoc not installed. Install weasyprint or pandoc for PDF generation.")
    except subprocess.CalledProcessError as e:
        print(f"[WARN] pandoc PDF generation failed: {e}")
    finally:
        html_tmp = pdf_path.replace(".pdf", ".tmp.html")
        if os.path.exists(html_tmp):
            os.remove(html_tmp)

    return False


def main():
    parser = argparse.ArgumentParser(description="SolidityGuard Report Generator")
    parser.add_argument("input", help="Path to scan results JSON file")
    parser.add_argument("--output", "-o", required=True, help="Output file path (.md)")
    parser.add_argument("--pdf", action="store_true", help="Also generate PDF")
    parser.add_argument("--project", default="", help="Project name")
    parser.add_argument("--client", default="", help="Client name")

    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Error: Input file '{args.input}' not found")
        sys.exit(1)

    with open(args.input) as f:
        data = json.load(f)

    report = generate_report(data, args.project, args.client)

    with open(args.output, "w") as f:
        f.write(report)
    print(f"Report written to {args.output}")

    if args.pdf:
        pdf_path = args.output.replace(".md", ".pdf")
        if generate_pdf(data, pdf_path, args.project, args.client):
            print(f"PDF written to {pdf_path}")
        else:
            print("[WARN] PDF generation failed. Install weasyprint: pip install weasyprint")


if __name__ == "__main__":
    main()
